name: Android Build

on:
  workflow_call:
    inputs:
      NVMRC:
        required: true
        type: string

jobs:
  build_example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node ${{ inputs.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NVMRC }}

      - name: Setup JDK zulu 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Enable Corepack
        run: corepack enable

      - run: yarn install --immutable --check-cache
        working-directory: packages/react-native-app

      - run: ./gradlew assemble
        working-directory: packages/react-native-app/android

      - uses: dniHze/maestro-test-action@v1
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          ram-size: 2048M
          target: default
          script: maestro test --format=junit --output=report.xml --no-ansi .maestro
        env:
          MAESTRO_CLI_NO_ANALYTICS: true
